name: android_ci
on:
  push:
    branches:
     - ["masters","develop"]

  pull_request:
    branches:
      - ["masters"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v2

     - name: Setup_Java_SDK
       uses: actions/setup-java@v2
       with:
         java-version: '17'
         distribution: 'temurin'

     - name: setup_gradle
       run : chmod+x gradlew

     - name: run gradle
       run : ./gradlew build

     - name: create debug build
       run : ./gradlew assembleDebug